### PR TITLE
Remove GLOB_NOSORT from glob so entries are sorted.

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by fwyzard** [comment]
what sorting is used ?

**Comment by gartung** [comment]
Directory order. This makes the menu unordered. This makes it hard to find specific dates or workflows.

**Comment by fwyzard** [comment]
Sure, what I meant is: if we remove `NO_SORT`, what sorting order is used ?

**Comment by gartung** [comment]
Alphabetic

**Comment by fwyzard** [comment]
ok, thanks

**Pull request merged**
